version: 2.1

orbs:
  gh: circleci/github-cli@2.1.1
  
jobs:
 build:
    docker:
      - image: cimg/node:current
    steps:
     - checkout
     - run:
          name: generate version file
          command: date +"1.%Y%m%d.1%H%M%S" > fans/version.txt
     - run:
          name: get tiles
          command: git clone --depth=1 --branch main https://github.com/lancard/korea-openstreetmap-tiles.git fans/tiles
     - run:
          name: remove unnecessary files
          command: cd fans/tiles && rm -rf clear.sh index.js README.md .git .gitignore
     - run:
          name: compress to zip
          command: cd fans && zip -q -r ../fans.zip *
     - gh/setup
     - run:
          name: release zip
          command: VERSION_STRING=`cat fans/version.txt` && gh release create $VERSION_STRING fans.zip
