name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: generate version string
        run: VERSION_STRING=`date +"1.%Y%m%d.1%H%M%S"` && echo "VERSION_STRING=$VERSION_STRING" >> $GITHUB_ENV

      - name: generate version file
        run: echo "${{ env.VERSION_STRING }}" > fans/version.txt
      
      - name: submodule update (tiles)
        run: git submodule update --init --recursive --remote
       
      - name: remove unnecessary files
        run: cd fans/tiles && rm -rf README.md .git .github
      
      - name: compress to zip
        run: cd fans && zip -q -r ../fans.zip *

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION_STRING }}
          release_name: Release ${{ env.VERSION_STRING }}
          draft: false
          prerelease: false

      - name: upload release zip file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fans.zip
          asset_name: fans.zip
          asset_content_type: application/zip
