name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: generate version file
      run: date +"1.%Y%m%d.1%H%M%S" > fans/version.txt
      
    - name: submodule update (tiles)
      run: git submodule update --init --recursive
      
    - name: remove unnecessary files
      run: cd fans/tiles && rm -rf clear.sh index.js README.md .git .gitignore
      
    - name: compress to zip
      run: cd fans && zip -q -r ../fans.zip *

    - name: release zip
      run: VERSION_STRING=`cat fans/version.txt` && gh release create $VERSION_STRING fans.zip
